### ISSUE TITLE
为什么不采用code LLM来做相关的任务

### ISSUE THREAD

**Issue by Jacksonlark** [eosphoros-ai/DB-GPT-Hub#10]
NL2SQL或者Text2SQL是一个代码生成任务，为什么不采用CodeLLM来做呢
如https://huggingface.co/Salesforce/codet5p-6b

**Comment by csunny** [comment]
目前像很多代码类的模型底座确实也是我们考虑的方向， 但在我们微调与使用过程中发现，对于写SQL这类复杂任务来讲，一个具有更好的推理与理解能力的底座，上限比单一的代码模型底座更高。 

当然这也不是确定的答案，我们也在结合各种底座做更多的尝试。如果你有结合代码底座更好的效果与方法，也期望能分享探讨。

**Comment by csunny** [comment]
Already support codeLlama
