### ISSUE TITLE
执行train_sft.sh 抛错

### ISSUE THREAD

**Issue by gantao21** [eosphoros-ai/DB-GPT-Hub#103]
![image](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/19900713/2aa80867-d639-44ab-9bd0-3d0603ac50b1)

![image](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/19900713/4d94d1c7-87b4-47b3-9492-3d570f1a27b2)

**Comment by gantao21** [comment]
我先试着改下--lora_target

**Comment by wangzaistone** [comment]
> 我先试着改下--lora_target
yes, the LLM model you used is LLama series, and the target param value should be the respond value ,and details you can refer the README.md
