### ISSUE TITLE
Lora 4bit微调报错

### ISSUE THREAD

**Issue by oushu1zhangxiangxuan1** [eosphoros-ai/DB-GPT-Hub#106]
```
W&B offline. Running your script from this directory will only write metadata locally. Use wandb disabled to completely turn off W&B.
/root/space/conda_envs/dbgpt_hub/lib/python3.10/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
/root/space/conda_envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/root/space/conda_envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
[2023-10-25 14:06:21,317] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/root/space/conda_envs/dbgpt_hub/lib/python3.10/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
10/25/2023 14:06:23 - WARNING - dbgpt_hub.llm_base.config_parser - We recommend enable mixed precision training.
10/25/2023 14:06:23 - WARNING - dbgpt_hub.llm_base.config_parser - `ddp_find_unused_parameters` needs to be set as False for LoRA in DDP training.
[INFO|training_args.py:1332] 2023-10-25 14:06:23,088 >> Found safetensors installation, but --save_safetensors=False. Safetensors should be a preferred weights saving format due to security and performance reasons. If your model cannot be saved by safetensors please feel free to open an issue at https://github.com/huggingface/safetensors!
[INFO|training_args.py:1764] 2023-10-25 14:06:23,088 >> PyTorch: setting up devices
/root/space/conda_envs/dbgpt_hub/lib/python3.10/site-packages/transformers/training_args.py:1677: FutureWarning: `--push_to_hub_token` is deprecated and will be removed in version 5 of 🤗 Transformers. Use `--hub_token` instead.
  warnings.warn(
10/25/2023 14:06:23 - INFO - dbgpt_hub.llm_base.config_parser - Process rank: 0, device: cpu, n_gpu: 1
  distributed training: True, compute dtype: torch.float16
10/25/2023 14:06:23 - INFO - dbgpt_hub.llm_base.config_parser - Training/evaluation parameters Seq2SeqTrainingArguments(
_n_gpu=1,
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_pin_memory=True,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=False,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
dispatch_batches=None,
do_eval=False,
do_predict=False,
do_train=True,
eval_accumulation_steps=None,
eval_delay=0,
eval_steps=None,
evaluation_strategy=no,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
generation_config=None,
generation_max_length=None,
generation_num_beams=None,
gradient_accumulation_steps=4,
gradient_checkpointing=False,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
load_best_model_at_end=False,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=dbgpt_hub/output/adapter/baichuan2-13b-qlora/runs/Oct25_14-06-23_v1002,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=10,
logging_strategy=steps,
lr_scheduler_type=cosine_with_restarts,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=None,
mp_parameters=,
no_cuda=False,
num_train_epochs=0.2,
optim=adamw_torch,
optim_args=None,
output_dir=dbgpt_hub/output/adapter/baichuan2-13b-qlora,
overwrite_output_dir=True,
past_index=-1,
per_device_eval_batch_size=8,
per_device_train_batch_size=1,
predict_with_generate=False,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=['wandb'],
resume_from_checkpoint=None,
run_name=dbgpt_hub/output/adapter/baichuan2-13b-qlora,
save_on_each_node=False,
save_safetensors=False,
save_steps=10,
save_strategy=steps,
save_total_limit=None,
seed=42,
sharded_ddp=[],
skip_memory_metrics=True,
sortish_sampler=False,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_cpu=False,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.0,
)
10/25/2023 14:06:23 - INFO - dbgpt_hub.data_process.data_utils - Loading dataset example_text2sql_train.json...
10/25/2023 14:06:23 - WARNING - dbgpt_hub.data_process.data_utils - Checksum failed: missing SHA-1 hash value in dataset_info.json.
/root/space/conda_envs/dbgpt_hub/lib/python3.10/site-packages/datasets/load.py:2089: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=None' instead.
  warnings.warn(
Using custom data configuration default-0c50abad2bd7e7b1
Loading Dataset Infos from /root/space/conda_envs/dbgpt_hub/lib/python3.10/site-packages/datasets/packaged_modules/json
Overwrite dataset info from restored data version if exists.
Loading Dataset info from /root/.cache/huggingface/datasets/json/default-0c50abad2bd7e7b1/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96
Found cached dataset json (/root/.cache/huggingface/datasets/json/default-0c50abad2bd7e7b1/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96)
Loading Dataset info from /root/.cache/huggingface/datasets/json/default-0c50abad2bd7e7b1/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96
[INFO|tokenization_utils_base.py:1850] 2023-10-25 14:06:23,971 >> loading file tokenizer.model
[INFO|tokenization_utils_base.py:1850] 2023-10-25 14:06:23,971 >> loading file added_tokens.json
[INFO|tokenization_utils_base.py:1850] 2023-10-25 14:06:23,971 >> loading file special_tokens_map.json
[INFO|tokenization_utils_base.py:1850] 2023-10-25 14:06:23,971 >> loading file tokenizer_config.json
[INFO|configuration_utils.py:713] 2023-10-25 14:06:24,031 >> loading configuration file /root/space/models/baichuan-inc/Baichuan2-13B-Chat/main/config.json
[INFO|configuration_utils.py:713] 2023-10-25 14:06:24,032 >> loading configuration file /root/space/models/baichuan-inc/Baichuan2-13B-Chat/main/config.json
[INFO|configuration_utils.py:775] 2023-10-25 14:06:24,033 >> Model config BaichuanConfig {
  "_from_model_config": true,
  "_name_or_path": "/root/space/models/baichuan-inc/Baichuan2-13B-Chat/main",
  "architectures": [
    "BaichuanForCausalLM"
  ],
  "auto_map": {
    "AutoConfig": "configuration_baichuan.BaichuanConfig",
    "AutoModelForCausalLM": "modeling_baichuan.BaichuanForCausalLM"
  },
  "bos_token_id": 1,
  "eos_token_id": 2,
  "gradient_checkpointing": [
    false
  ],
  "hidden_act": "silu",
  "hidden_size": 5120,
  "initializer_range": 0.02,
  "intermediate_size": 13696,
  "model_max_length": 4096,
  "model_type": "baichuan",
  "num_attention_heads": 40,
  "num_hidden_layers": 40,
  "pad_token_id": 0,
  "rms_norm_eps": 1e-06,
  "tie_word_embeddings": false,
  "tokenizer_class": "BaichuanTokenizer",
  "torch_dtype": "bfloat16",
  "transformers_version": "4.33.2",
  "use_cache": true,
  "vocab_size": 125696,
  "z_loss_weight": 0
}

10/25/2023 14:06:24 - INFO - dbgpt_hub.llm_base.load_tokenizer - Quantizing model to 4 bit.
Traceback (most recent call last):
  File "/mnt/datadisk0/repos/eosphoros-ai/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 151, in <module>
    train()
  File "/mnt/datadisk0/repos/eosphoros-ai/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 128, in train
    run_sft(
  File "/mnt/datadisk0/repos/eosphoros-ai/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 35, in run_sft
    model, tokenizer = load_model_and_tokenizer(
  File "/mnt/datadisk0/repos/eosphoros-ai/DB-GPT-Hub/dbgpt_hub/llm_base/load_tokenizer.py", line 261, in load_model_and_tokenizer
    model = AutoModelForCausalLM.from_pretrained(
  File "/root/space/conda_envs/dbgpt_hub/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(
  File "/root/.cache/huggingface/modules/transformers_modules/main/modeling_baichuan.py", line 670, in from_pretrained
    return super(BaichuanForCausalLM, cls).from_pretrained(pretrained_model_name_or_path, *model_args, 
  File "/root/space/conda_envs/dbgpt_hub/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2494, in from_pretrained
    raise ImportError(
ImportError: Using `load_in_8bit=True` requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes `pip install -i https://test.pypi.org/simple/ bitsandbytes` or pip install bitsandbytes` 
```

```sh
pip list |grep bits
bitsandbytes                  0.41.0
pip list |grep acc
accelerate                    0.21.0
```

**Comment by wangzaistone** [comment]
> ```
> W&B offline. Running your script from this directory will only write metadata locally. Use wandb disabled to completely turn off W&B.
> /root/space/conda_envs/dbgpt_hub/lib/python3.10/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
>   return torch._C._cuda_getDeviceCount() > 0
> /root/space/conda_envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
>   warn("The installed version of bitsandbytes was compiled without GPU support. "
> /root/space/conda_envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
> [2023-10-25 14:06:21,317] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
> /root/space/conda_envs/dbgpt_hub/lib/python3.10/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
>   warnings.warn(
> 10/25/2023 14:06:23 - WARNING - dbgpt_hub.llm_base.config_parser - We recommend enable mixed precision training.
> 10/25/2023 14:06:23 - WARNING - dbgpt_hub.llm_base.config_parser - `ddp_find_unused_parameters` needs to be set as False for LoRA in DDP training.
> [INFO|training_args.py:1332] 2023-10-25 14:06:23,088 >> Found safetensors installation, but --save_safetensors=False. Safetensors should be a preferred weights saving format due to security and performance reasons. If your model cannot be saved by safetensors please feel free to open an issue at https://github.com/huggingface/safetensors!
> [INFO|training_args.py:1764] 2023-10-25 14:06:23,088 >> PyTorch: setting up devices
> /root/space/conda_envs/dbgpt_hub/lib/python3.10/site-packages/transformers/training_args.py:1677: FutureWarning: `--push_to_hub_token` is deprecated and will be removed in version 5 of 🤗 Transformers. Use `--hub_token` instead.
>   warnings.warn(
> 10/25/2023 14:06:23 - INFO - dbgpt_hub.llm_base.config_parser - Process rank: 0, device: cpu, n_gpu: 1
>   distributed training: True, compute dtype: torch.float16
> 10/25/2023 14:06:23 - INFO - dbgpt_hub.llm_base.config_parser - Training/evaluation parameters Seq2SeqTrainingArguments(
> _n_gpu=1,
> adafactor=False,
> adam_beta1=0.9,
> adam_beta2=0.999,
> adam_epsilon=1e-08,
> auto_find_batch_size=False,
> bf16=False,
> bf16_full_eval=False,
> data_seed=None,
> dataloader_drop_last=False,
> dataloader_num_workers=0,
> dataloader_pin_memory=True,
> ddp_backend=None,
> ddp_broadcast_buffers=None,
> ddp_bucket_cap_mb=None,
> ddp_find_unused_parameters=False,
> ddp_timeout=1800,
> debug=[],
> deepspeed=None,
> disable_tqdm=False,
> dispatch_batches=None,
> do_eval=False,
> do_predict=False,
> do_train=True,
> eval_accumulation_steps=None,
> eval_delay=0,
> eval_steps=None,
> evaluation_strategy=no,
> fp16=False,
> fp16_backend=auto,
> fp16_full_eval=False,
> fp16_opt_level=O1,
> fsdp=[],
> fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_grad_ckpt': False},
> fsdp_min_num_params=0,
> fsdp_transformer_layer_cls_to_wrap=None,
> full_determinism=False,
> generation_config=None,
> generation_max_length=None,
> generation_num_beams=None,
> gradient_accumulation_steps=4,
> gradient_checkpointing=False,
> greater_is_better=None,
> group_by_length=False,
> half_precision_backend=auto,
> hub_always_push=False,
> hub_model_id=None,
> hub_private_repo=False,
> hub_strategy=every_save,
> hub_token=<HUB_TOKEN>,
> ignore_data_skip=False,
> include_inputs_for_metrics=False,
> jit_mode_eval=False,
> label_names=None,
> label_smoothing_factor=0.0,
> learning_rate=5e-05,
> length_column_name=length,
> load_best_model_at_end=False,
> local_rank=0,
> log_level=passive,
> log_level_replica=warning,
> log_on_each_node=True,
> logging_dir=dbgpt_hub/output/adapter/baichuan2-13b-qlora/runs/Oct25_14-06-23_v1002,
> logging_first_step=False,
> logging_nan_inf_filter=True,
> logging_steps=10,
> logging_strategy=steps,
> lr_scheduler_type=cosine_with_restarts,
> max_grad_norm=1.0,
> max_steps=-1,
> metric_for_best_model=None,
> mp_parameters=,
> no_cuda=False,
> num_train_epochs=0.2,
> optim=adamw_torch,
> optim_args=None,
> output_dir=dbgpt_hub/output/adapter/baichuan2-13b-qlora,
> overwrite_output_dir=True,
> past_index=-1,
> per_device_eval_batch_size=8,
> per_device_train_batch_size=1,
> predict_with_generate=False,
> prediction_loss_only=False,
> push_to_hub=False,
> push_to_hub_model_id=None,
> push_to_hub_organization=None,
> push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
> ray_scope=last,
> remove_unused_columns=True,
> report_to=['wandb'],
> resume_from_checkpoint=None,
> run_name=dbgpt_hub/output/adapter/baichuan2-13b-qlora,
> save_on_each_node=False,
> save_safetensors=False,
> save_steps=10,
> save_strategy=steps,
> save_total_limit=None,
> seed=42,
> sharded_ddp=[],
> skip_memory_metrics=True,
> sortish_sampler=False,
> tf32=None,
> torch_compile=False,
> torch_compile_backend=None,
> torch_compile_mode=None,
> torchdynamo=None,
> tpu_metrics_debug=False,
> tpu_num_cores=None,
> use_cpu=False,
> use_ipex=False,
> use_legacy_prediction_loop=False,
> use_mps_device=False,
> warmup_ratio=0.0,
> warmup_steps=0,
> weight_decay=0.0,
> )
> 10/25/2023 14:06:23 - INFO - dbgpt_hub.data_process.data_utils - Loading dataset example_text2sql_train.json...
> 10/25/2023 14:06:23 - WARNING - dbgpt_hub.data_process.data_utils - Checksum failed: missing SHA-1 hash value in dataset_info.json.
> /root/space/conda_envs/dbgpt_hub/lib/python3.10/site-packages/datasets/load.py:2089: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
> You can remove this warning by passing 'token=None' instead.
>   warnings.warn(
> Using custom data configuration default-0c50abad2bd7e7b1
> Loading Dataset Infos from /root/space/conda_envs/dbgpt_hub/lib/python3.10/site-packages/datasets/packaged_modules/json
> Overwrite dataset info from restored data version if exists.
> Loading Dataset info from /root/.cache/huggingface/datasets/json/default-0c50abad2bd7e7b1/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96
> Found cached dataset json (/root/.cache/huggingface/datasets/json/default-0c50abad2bd7e7b1/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96)
> Loading Dataset info from /root/.cache/huggingface/datasets/json/default-0c50abad2bd7e7b1/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96
> [INFO|tokenization_utils_base.py:1850] 2023-10-25 14:06:23,971 >> loading file tokenizer.model
> [INFO|tokenization_utils_base.py:1850] 2023-10-25 14:06:23,971 >> loading file added_tokens.json
> [INFO|tokenization_utils_base.py:1850] 2023-10-25 14:06:23,971 >> loading file special_tokens_map.json
> [INFO|tokenization_utils_base.py:1850] 2023-10-25 14:06:23,971 >> loading file tokenizer_config.json
> [INFO|configuration_utils.py:713] 2023-10-25 14:06:24,031 >> loading configuration file /root/space/models/baichuan-inc/Baichuan2-13B-Chat/main/config.json
> [INFO|configuration_utils.py:713] 2023-10-25 14:06:24,032 >> loading configuration file /root/space/models/baichuan-inc/Baichuan2-13B-Chat/main/config.json
> [INFO|configuration_utils.py:775] 2023-10-25 14:06:24,033 >> Model config BaichuanConfig {
>   "_from_model_config": true,
>   "_name_or_path": "/root/space/models/baichuan-inc/Baichuan2-13B-Chat/main",
>   "architectures": [
>     "BaichuanForCausalLM"
>   ],
>   "auto_map": {
>     "AutoConfig": "configuration_baichuan.BaichuanConfig",
>     "AutoModelForCausalLM": "modeling_baichuan.BaichuanForCausalLM"
>   },
>   "bos_token_id": 1,
>   "eos_token_id": 2,
>   "gradient_checkpointing": [
>     false
>   ],
>   "hidden_act": "silu",
>   "hidden_size": 5120,
>   "initializer_range": 0.02,
>   "intermediate_size": 13696,
>   "model_max_length": 4096,
>   "model_type": "baichuan",
>   "num_attention_heads": 40,
>   "num_hidden_layers": 40,
>   "pad_token_id": 0,
>   "rms_norm_eps": 1e-06,
>   "tie_word_embeddings": false,
>   "tokenizer_class": "BaichuanTokenizer",
>   "torch_dtype": "bfloat16",
>   "transformers_version": "4.33.2",
>   "use_cache": true,
>   "vocab_size": 125696,
>   "z_loss_weight": 0
> }
> 
> 10/25/2023 14:06:24 - INFO - dbgpt_hub.llm_base.load_tokenizer - Quantizing model to 4 bit.
> Traceback (most recent call last):
>   File "/mnt/datadisk0/repos/eosphoros-ai/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 151, in <module>
>     train()
>   File "/mnt/datadisk0/repos/eosphoros-ai/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 128, in train
>     run_sft(
>   File "/mnt/datadisk0/repos/eosphoros-ai/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 35, in run_sft
>     model, tokenizer = load_model_and_tokenizer(
>   File "/mnt/datadisk0/repos/eosphoros-ai/DB-GPT-Hub/dbgpt_hub/llm_base/load_tokenizer.py", line 261, in load_model_and_tokenizer
>     model = AutoModelForCausalLM.from_pretrained(
>   File "/root/space/conda_envs/dbgpt_hub/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
>     return model_class.from_pretrained(
>   File "/root/.cache/huggingface/modules/transformers_modules/main/modeling_baichuan.py", line 670, in from_pretrained
>     return super(BaichuanForCausalLM, cls).from_pretrained(pretrained_model_name_or_path, *model_args, 
>   File "/root/space/conda_envs/dbgpt_hub/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2494, in from_pretrained
>     raise ImportError(
> ImportError: Using `load_in_8bit=True` requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes `pip install -i https://test.pypi.org/simple/ bitsandbytes` or pip install bitsandbytes` 
> ```
> 
> ```shell
> pip list |grep bits
> bitsandbytes                  0.41.0
> pip list |grep acc
> accelerate                    0.21.0
> ```

you can try  bitsandbytes    0.41.1

**Comment by oushu1zhangxiangxuan1** [comment]
> ```shell
> bitsandbytes
> ```

Thanks. But it still doesn't work.

```
10/26/2023 16:09:44 - INFO - dbgpt_hub.llm_base.load_tokenizer - Quantizing model to 4 bit.
Traceback (most recent call last):
  File "/mnt/datadisk0/repos/eosphoros-ai/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 151, in <module>
    train()
  File "/mnt/datadisk0/repos/eosphoros-ai/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 128, in train
    run_sft(
  File "/mnt/datadisk0/repos/eosphoros-ai/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 35, in run_sft
    model, tokenizer = load_model_and_tokenizer(
  File "/mnt/datadisk0/repos/eosphoros-ai/DB-GPT-Hub/dbgpt_hub/llm_base/load_tokenizer.py", line 261, in load_model_and_tokenizer
    model = AutoModelForCausalLM.from_pretrained(
  File "/root/space/conda_envs/dbgpt_hub/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(
  File "/root/.cache/huggingface/modules/transformers_modules/main/modeling_baichuan.py", line 670, in from_pretrained
    return super(BaichuanForCausalLM, cls).from_pretrained(pretrained_model_name_or_path, *model_args, 
  File "/root/space/conda_envs/dbgpt_hub/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2494, in from_pretrained
    raise ImportError(
ImportError: Using `load_in_8bit=True` requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes `pip install -i https://test.pypi.org/simple/ bitsandbytes` or pip install bitsandbytes` 
(/root/space/conda_envs/dbgpt_hub) [root@v1002 DB-GPT-Hub]# pip list|grep bits
bitsandbytes                  0.41.1

pip install -i https://test.pypi.org/simple/ bitsandbytes
Looking in indexes: https://test.pypi.org/simple/
Requirement already satisfied: bitsandbytes in /mnt/datadisk0/conda_envs/dbgpt_hub/lib/python3.10/site-packages (0.41.1)
```

**Comment by wangzaistone** [comment]
> > ```shell
> > bitsandbytes
> > ```
> 
> Thanks. But it still doesn't work.
> 
> ```
> 10/26/2023 16:09:44 - INFO - dbgpt_hub.llm_base.load_tokenizer - Quantizing model to 4 bit.
> Traceback (most recent call last):
>   File "/mnt/datadisk0/repos/eosphoros-ai/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 151, in <module>
>     train()
>   File "/mnt/datadisk0/repos/eosphoros-ai/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 128, in train
>     run_sft(
>   File "/mnt/datadisk0/repos/eosphoros-ai/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 35, in run_sft
>     model, tokenizer = load_model_and_tokenizer(
>   File "/mnt/datadisk0/repos/eosphoros-ai/DB-GPT-Hub/dbgpt_hub/llm_base/load_tokenizer.py", line 261, in load_model_and_tokenizer
>     model = AutoModelForCausalLM.from_pretrained(
>   File "/root/space/conda_envs/dbgpt_hub/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
>     return model_class.from_pretrained(
>   File "/root/.cache/huggingface/modules/transformers_modules/main/modeling_baichuan.py", line 670, in from_pretrained
>     return super(BaichuanForCausalLM, cls).from_pretrained(pretrained_model_name_or_path, *model_args, 
>   File "/root/space/conda_envs/dbgpt_hub/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2494, in from_pretrained
>     raise ImportError(
> ImportError: Using `load_in_8bit=True` requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes `pip install -i https://test.pypi.org/simple/ bitsandbytes` or pip install bitsandbytes` 
> (/root/space/conda_envs/dbgpt_hub) [root@v1002 DB-GPT-Hub]# pip list|grep bits
> bitsandbytes                  0.41.1
> 
> pip install -i https://test.pypi.org/simple/ bitsandbytes
> Looking in indexes: https://test.pypi.org/simple/
> Requirement already satisfied: bitsandbytes in /mnt/datadisk0/conda_envs/dbgpt_hub/lib/python3.10/site-packages (0.41.1)
> ```

你的GPU和cuda版本是怎样的？有更新代码重新安装requirements中的内容吗？运行命令这些要不都贴下？

**Comment by oushu1zhangxiangxuan1** [comment]
code 是最新的，我重新整个conda环境试下
```
commit abdf1e3dd23991ff912a29ab5f3937e12e8c9ec5
Author: wangzaistone <zhaowanghappy@163.com>
Date:   Mon Oct 23 21:50:41 2023 +0800

    update the released weights info
```

**Comment by oushu1zhangxiangxuan1** [comment]
cudatoolkit用的11.8

**Comment by oushu1zhangxiangxuan1** [comment]
nvidia-smi
```
Fri Oct 27 10:30:53 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.102.04   Driver Version: 450.102.04   CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:09.0 Off |                  Off |
| N/A   32C    P0    25W / 300W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:00:0A.0 Off |                    0 |
| N/A   36C    P0    27W / 300W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by oushu1zhangxiangxuan1** [comment]
pip install requirements 
![image](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/39079736/a1b1f5cd-2821-4a71-abf6-e95912da9bc0)
cudnn 安装的12(torch>=1.13.1  的依赖？)
![image](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/39079736/49f24511-1791-4429-a241-9fa71880fcd8)

**Comment by oushu1zhangxiangxuan1** [comment]
nvcc
```shell
(/root/space/conda_envs/dbgpt_hub) [root@v1002 DB-GPT-Hub]# locate nvcc
/usr/local/cuda-11.0/bin/nvcc
(/root/space/conda_envs/dbgpt_hub) [root@v1002 DB-GPT-Hub]# /usr/local/cuda-11.0/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
```

**Comment by oushu1zhangxiangxuan1** [comment]
命令
```shell
CUDA_VISIBLE_DEVICES=0 python dbgpt_hub/train/sft_train.py \
    --quantization_bit 4 \
    --model_name_or_path /root/space/models/baichuan-inc/Baichuan2-13B-Chat/main \
    --do_train \
    --dataset example_text2sql \
    --max_source_length 1024 \
    --max_target_length 512 \
    --template baichuan2 \
    --finetuning_type lora \
    --lora_rank 32 \
    --lora_alpha 8 \
    --lora_target W_pack \
    --output_dir dbgpt_hub/output/adapter/baichuan2-13b-qlora \
    --overwrite_cache \
    --overwrite_output_dir \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine_with_restarts \
    --logging_steps 10 \
    --save_steps 10 \
    --learning_rate 5e-5 \
    --num_train_epochs 0.2 \
    --plot_loss 
```

**Comment by oushu1zhangxiangxuan1** [comment]
torch version
```
pip list|grep torch
torch                         2.1.0
```

**Comment by wangzaistone** [comment]
> torch version
> 
> ```
> pip list|grep torch
> torch                         2.1.0
> ```

你看看这个bitandbtyes的官方issue ，https://github.com/TimDettmers/bitsandbytes/issues/837

**Comment by wangzaistone** [comment]
这个我也没遇到过

**Comment by 489597448** [comment]
我也遇到这种问题了   最后解决了吗

**Comment by oushu1zhangxiangxuan1** [comment]
还没，今天再试试

**Comment by oushu1zhangxiangxuan1** [comment]
> > torch version
> > ```
> > pip list|grep torch
> > torch                         2.1.0
> > ```
> 
> 你看看这个bitandbtyes的官方issue ，[TimDettmers/bitsandbytes#837](https://github.com/TimDettmers/bitsandbytes/issues/837)

多谢

**Comment by 489597448** [comment]
改了torch的版本&nbsp; 后边还会出现新的问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月30日(周一) 上午10:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [eosphoros-ai/DB-GPT-Hub] Lora 4bit微调报错 (Issue #106)




   
torch version
 pip list|grep torch torch                         2.1.0   
你看看这个bitandbtyes的官方issue ，TimDettmers/bitsandbytes#837
  
多谢

**Comment by oushu1zhangxiangxuan1** [comment]
貌似和torch、cuda等版本无关，试了不同版本，会有同样错误

**Comment by oushu1zhangxiangxuan1** [comment]
Solved by re-create a whole new conda env

And should install torch following torch official website:  (which may block sometimes)
```shell
conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.6 -c pytorch -c nvidia
```

Thanks for help @wangzaistone
