### ISSUE TITLE
How to run on Mac

### ISSUE THREAD

**Issue by cloud-bear** [eosphoros-ai/DB-GPT-Hub#111]
<img width="712" alt="image" src="https://github.com/eosphoros-ai/DB-GPT-Hub/assets/34566110/7fa64324-8044-4a7f-ba32-a9a57284e116">

**Comment by wangzaistone** [comment]
> <img alt="image" width="712" src="https://user-images.githubusercontent.com/34566110/278849322-7fa64324-8044-4a7f-ba32-a9a57284e116.png">

so far , it needs to be on a server with GPU.  SFT traing needs compute resource .
