### ISSUE TITLE
Evaluation indicators need to be updated 

### ISSUE THREAD

**Issue by JBoRu** [eosphoros-ai/DB-GPT-Hub#119]
Hi,
 Thanks for this good project! However, the evaluation procedure is incorrect leading to an overestimated result. Specifically, your project uses the test-suit evaluation over the database which is used in original execution accuracy. According to the [official evaluation project](https://github.com/taoyds/test-suite-sql-eval), you should use the new database_ts instead of the database. Therefore, the results will be lower! Here are my evaluation results of CodeLLama-13B-instruct-lora (the parameter config is same with your provided config) on the original database (78.1) and the correct database_ts (70.9).

![截屏2023-11-02 20 31 07](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/38073482/a6cb301d-9e7c-40b7-917e-87d2912a2210)
![截屏2023-11-02 20 31 24](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/38073482/8735fde0-09c2-4410-9ea7-ce945bfae1c1)

**Comment by wangzaistone** [comment]
> Hi, Thanks for this good project! However, the evaluation procedure is incorrect leading to an overestimated result. Specifically, your project uses the test-suit evaluation over the database which is used in original execution accuracy. According to the [official evaluation project](https://github.com/taoyds/test-suite-sql-eval), you should use the new database_ts instead of the database. Therefore, the results will be lower! Here are my evaluation results of CodeLLama-13B-instruct-lora (the parameter config is same with your provided config) on the original database (78.1) and the correct database_ts (70.9).
> 
> ![截屏2023-11-02 20 31 07](https://user-images.githubusercontent.com/38073482/279983241-a6cb301d-9e7c-40b7-917e-87d2912a2210.png) ![截屏2023-11-02 20 31 24](https://user-images.githubusercontent.com/38073482/279983296-8735fde0-09c2-4410-9ea7-ce945bfae1c1.png)

thanks for your suggestion， but I still  don't understand what's the detail  about the  " new database_ts " , we are followed the same link as you provide.  And the dev  dataset which include 1034 examples  is the linked github gived . If possible , may I get your wechat or other contact way ?My wechat is dabing3520 .  And may be we could discuss face to face in LiDeBuilding  in No. 59, Zhongguancun Street, Haidian Dist. on  weekends .
thanks for your attention again!

**Comment by wangzaistone** [comment]
> the parameter config is same with your provided config 
Junior brother， What you has talked is important to the project especially in the expriments， we  look forward to discuss with you together  if it's possible .  And  About the  metric in spider trained set  as the project used now , several guys has reproducible experimental results which are all above 0.789  metric in several wechat group  refer the params as we provided . And the  adapter  I trained has opened in Hugging Face [CodeLlama-13b-sql-lora](https://huggingface.co/eosphoros/CodeLlama-13b-sql-lora). We cannot ensure that all experiments are the same , After all, the large model itself has a certain degree of randomness, especially such as  the temperature setting.  It's very nice for you to talk about it .

**Comment by wangzaistone** [comment]
> Hi, Thanks for this good project! However, the evaluation procedure is incorrect leading to an overestimated result. Specifically, your project uses the test-suit evaluation over the database which is used in original execution accuracy. According to the [official evaluation project](https://github.com/taoyds/test-suite-sql-eval), you should use the new database_ts instead of the database. Therefore, the results will be lower! Here are my evaluation results of CodeLLama-13B-instruct-lora (the parameter config is same with your provided config) on the original database (78.1) and the correct database_ts (70.9).
> 
> ![截屏2023-11-02 20 31 07](https://user-images.githubusercontent.com/38073482/279983241-a6cb301d-9e7c-40b7-917e-87d2912a2210.png) ![截屏2023-11-02 20 31 24](https://user-images.githubusercontent.com/38073482/279983296-8735fde0-09c2-4410-9ea7-ce945bfae1c1.png)

> the parameter config is same with your provided config 
Junior brother， What you has talked is important to the project especially in the expriments， we  look forward to discuss with you together  if it's possible .  And  About the  metric in spider trained set  as the project used now , several guys has reproducible experimental results which are all above 0.789  metric in several wechat group  refer the params as we provided . And the  adapter  I trained has opened in Hugging Face [CodeLlama-13b-sql-lora](https://huggingface.co/eosphoros/CodeLlama-13b-sql-lora). We cannot ensure that all experiments are the same , After all, the large model itself has a certain degree of randomness, especially such as  the temperature setting.  It's very nice for you to talk about it .

**Comment by wangzaistone** [comment]
If you have better eval code , Could you contribute  a pr for us ,thanks a lot ~

**Comment by wangzaistone** [comment]
According to what you pointed out, the database in  evaluation method is updated，which from the database downloaded from the original official [yale website](https://yale-lily.github.io/spider)(spider dataset 95Mb)  to the database pointed to downloaded from the author's github linked to(1.27Gb） , and the index has dropped . The indicators after re-forecasting and evaluating based on the weights we uploaded to [HF](https://huggingface.co/eosphoros/CodeLlama-13b-sql-lora/blob/main/README.md)  exe acc is   0.742 as follows, which are slightly different from yours.
<img width="765" alt="image" src="https://github.com/eosphoros-ai/DB-GPT-Hub/assets/26740509/89cf97a9-9081-40a3-b013-f8bd4d742fca">


Thanks again for your reminder.

**Comment by wangzaistone** [comment]
I update the ex acc , before we use around 50k data to trained in codellama-13 , the eval score 0.825 in before 95Mb database evaluated, now after change the database as your remind , the exe acc  is  0.764。 
![image](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/26740509/c159d710-fdcb-4f46-8463-006503acfc76)

**Comment by AlphaNext** [comment]
@wangzaistone Thanks for your nice work, could you add these two different dataset links (spider dataset 95mb and anther 1.27gb), i can't find the 1.27gb version, thanks.

**Comment by junewgl** [comment]
> @wangzaistone Thanks for your nice work, could you add these two different dataset links (spider dataset 95mb and anther 1.27gb), i can't find the 1.27gb version, thanks.
> 
> 0.825 (95mb) and 0.764(1.27gb) are test on the **spider dev dataset** or **spider test dataset**?

test on dev. ts eval dataset is here:https://github.com/taoyds/test-suite-sql-eval @AlphaNext
