### ISSUE TITLE
中文版里仍然是“pip install -r requirements.txt ”，需要更新一下。

### ISSUE THREAD

**Issue by ccutyear** [eosphoros-ai/DB-GPT-Hub#131]
中文版里仍然是“pip install -r requirements.txt ”，需要更新成“poetry install”。

**Comment by GuohuanFeng0** [comment]
![Snipaste_2023-11-13_19-52-02](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/144611882/cf32ed98-6ef1-4cca-aa6b-af936b1eb2c8)
poetry install这样会报错你您知道是为什么吗

**Comment by wangzaistone** [comment]
> 中文版里仍然是“pip install -r requirements.txt ”，需要更新成“poetry install”。

OK，thanks for your remind
