### ISSUE TITLE
poetry install error

### ISSUE THREAD

**Issue by GuohuanFeng0** [eosphoros-ai/DB-GPT-Hub#132]
![Snipaste_2023-11-13_19-52-02](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/144611882/06d74327-baf0-484c-a79f-c742593145da)

**Comment by wangzaistone** [comment]
This is your poetry version error , you could follow this steps :
`conda remove poetry
conda install -c conda-forge poetry>=1.4.0

`
