### ISSUE TITLE
error poetry run sh dbgpt_hub/scripts/gen_train_eval_data.sh error

### ISSUE THREAD

**Issue by GuohuanFeng0** [eosphoros-ai/DB-GPT-Hub#134]
the dataset spider already in the correct location 
![spider error](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/144611882/40dfe0d6-16f0-4832-8453-b39d392dfdee)
but still get a error when i run  poetry run sh dbgpt_hub/scripts/gen_train_eval_data.sh error

(dbgpt_hub1) dbgpt@anyi-Precision-5820-Tower-X-Series:~/DB-GPT-Hub$ poetry run sh dbgpt_hub/scripts/gen_train_eval_data.sh
Traceback (most recent call last):
  File "/home/dbgpt/miniconda3/envs/dbgpt_hub1/lib/python3.10/site-packages/torch/__init__.py", line 174, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/dbgpt/miniconda3/envs/dbgpt_hub1/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcufft.so.11: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dbgpt/DB-GPT-Hub/dbgpt_hub/data_process/sql_data_process.py", line 11, in <module>
    from dbgpt_hub.configs.config import (
  File "/home/dbgpt/DB-GPT-Hub/dbgpt_hub/configs/__init__.py", line 1, in <module>
    from .model_args import (
  File "/home/dbgpt/DB-GPT-Hub/dbgpt_hub/configs/model_args.py", line 2, in <module>
    import torch
  File "/home/dbgpt/miniconda3/envs/dbgpt_hub1/lib/python3.10/site-packages/torch/__init__.py", line 234, in <module>
    _load_global_deps()
  File "/home/dbgpt/miniconda3/envs/dbgpt_hub1/lib/python3.10/site-packages/torch/__init__.py", line 195, in _load_global_deps
    _preload_cuda_deps(lib_folder, lib_name)
  File "/home/dbgpt/miniconda3/envs/dbgpt_hub1/lib/python3.10/site-packages/torch/__init__.py", line 160, in _preload_cuda_deps
    raise ValueError(f"{lib_name} not found in the system path {sys.path}")
ValueError: libcublas.so.*[0-9] not found in the system path ['/home/dbgpt/DB-GPT-Hub/dbgpt_hub/data_process', '/home/dbgpt/miniconda3/envs/dbgpt_hub1/lib/python310.zip', '/home/dbgpt/miniconda3/envs/dbgpt_hub1/lib/python3.10', '/home/dbgpt/miniconda3/envs/dbgpt_hub1/lib/python3.10/lib-dynload', '/home/dbgpt/.local/lib/python3.10/site-packages', '/home/dbgpt/miniconda3/envs/dbgpt_hub1/lib/python3.10/site-packages', '/home/dbgpt/DB-GPT-Hub', '/home/dbgpt/DB-GPT-Hub']

**Comment by qidanrui** [comment]
Hi, @GuohuanFeng0. Firstly thanks for your interest in our project!

Could you please provide more details about your system environment with the following steps:

1. Check CUDA Installation:
First, ensure that you have CUDA properly installed on your system. You can do this by running the following command in your terminal to check the CUDA version:
```
nvcc --version
```
If CUDA is installed correctly, it will display the version information. If it's not installed, you'll need to install it following NVIDIA's official installation instructions for your specific operating system.

2. Verify cuBLAS Installation:
Make sure that the cuBLAS library is included as part of your CUDA installation. It should be located in the CUDA toolkit directory. You can check if it's present by looking for the library file:
```
ls /usr/local/cuda/lib64/libcublas.so.*
```
Replace /usr/local/cuda with the actual path to your CUDA installation directory.

3. Add CUDA Library Path to LD_LIBRARY_PATH:
To ensure that the cuBLAS library can be found, you should add the CUDA library path to your LD_LIBRARY_PATH. You can do this by running:
```
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
```
Replace /usr/local/cuda with the actual path to your CUDA installation directory.

4. Check Poetry Environment:
Ensure that you are running your Poetry-based project within a virtual environment that includes CUDA and cuBLAS. You might need to create a virtual environment and install your project dependencies within it.

5. Rebuild Your Project:
After making these changes, try rebuilding your Poetry project. If you are using Poetry for package management, run the following command in your project directory:
```
poetry install
```
This will ensure that your project dependencies are correctly installed within the virtual environment.

6. Check Your CUDA Code:
Make sure that your CUDA code is properly configured to use cuBLAS. You should include the necessary CUDA headers and link your code against the cuBLAS library.

**Comment by qidanrui** [comment]
Also, could you please provide your torch version to us? Thanks!

**Comment by qidanrui** [comment]
Hi, @GuohuanFeng0 
I've updated the `pyproject.toml` with cuda-related packages. You can download our newest version and test if there still error exists. Thanks for your interest again! More issues and suggestions are welcome!

**Comment by GuohuanFeng0** [comment]
> Hi, @GuohuanFeng0 I've updated the `pyproject.toml` with cuda-related packages. You can download our newest version and test if there still error exists. Thanks for your interest again! More issues and suggestions are welcome!
Wow thanks so much i will try it later

**Comment by GuohuanFeng0** [comment]
> Hi, @GuohuanFeng0 I've updated the `pyproject.toml` with cuda-related packages. You can download our newest version and test if there still error exists. Thanks for your interest again! More issues and suggestions are welcome!

Thanks so much i can set up environment now after i updated the pyproject.toml

**Comment by qidanrui** [comment]
Hi, @GuohuanFeng0 Great! Thanks for your interest again!!!!
