### ISSUE TITLE
在这些不同的 base_model上最后的评估结果是怎么样的呢？是采用同样的超参数嘛（learning rate, etc...）

### ISSUE THREAD

**Issue by JasonLLLLLLLLLLL** [eosphoros-ai/DB-GPT-Hub#142]

**Comment by qidanrui** [comment]
您说的“最后的评估结果”是指?
对于现有model的评估结果，可以参考“https://github.com/eosphoros-ai/DB-GPT-Hub/blob/main/docs/eval_llm_result.md”
