### ISSUE TITLE
Error occurs when finetuning Codellama-7b-instruct-hf with LoRA mode

### ISSUE THREAD

**Issue by qidanrui** [eosphoros-ai/DB-GPT-Hub#151]
When I fine-tuned the codellama-7b-instruct-hf under the LoRA mode (nothing changed in train_sft.sh) in my Colab Environment with Tesla V100 GPU 16G, and 51GB CPU memory, the following bug occurs: 
<img width="923" alt="Screen Shot 2023-11-30 at 4 22 31 PM" src="https://github.com/eosphoros-ai/DB-GPT-Hub/assets/10005367/48e9afdc-8076-4397-814c-76a1efdb9cc9">

However, if I change it to the QLoRA mode, the running process becomes normal.  
<img width="566" alt="Screen Shot 2023-11-30 at 4 24 13 PM" src="https://github.com/eosphoros-ai/DB-GPT-Hub/assets/10005367/ce26d7fe-0b0c-4135-9925-01033af8146f">

Could you please help me to test it under your A100 environment @wangzaistone ? Let us confirm whether it is a real bug~

**Comment by wangzaistone** [comment]
Sure, I have used the latest code to run in A100 , and update the env , the code run pass succ, there is no problem . Here is my script, 
```
wandb offline # Close wandb
# a100 ,单卡
current_date=$(date +"%Y%m%d_%H%M")
train_log="dbgpt_hub/output/logs/train_sft_test_${current_date}_issue151.log"
start_time=$(date +%s)
echo " Train Start time: $(date -d @$start_time +'%Y-%m-%d %H:%M:%S')" >>${train_log}

# the default param set could be run in a server with one a100(40G) gpu, if your server not support the set,you can set smaller param such as  lora_rank and use qlora with quant 4 eg...
CUDA_VISIBLE_DEVICES=0 python dbgpt_hub/train/sft_train.py \
    --model_name_or_path /home/model_files/CodeLlama-7b-Instruct-hf \
    --do_train \
    --dataset example_text2sql_train \
    --max_source_length 2048 \
    --max_target_length 512 \
    --finetuning_type lora \
    --lora_target q_proj,v_proj \
    --template llama2 \
    --lora_rank 64 \
    --lora_alpha 32 \
    --output_dir dbgpt_hub/output/adapter/CodeLlama-7-sql-lora_test_issue151 \
    --overwrite_cache \
    --overwrite_output_dir \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --lr_scheduler_type cosine_with_restarts \
    --logging_steps 10 \
    --save_steps 10 \
    --learning_rate 2e-4 \
    --num_train_epochs 0.1 \
    --plot_loss \
    --bf16  >> ${train_log}
    # --bf16#v100不支持bf16
    
echo "############train end###############" >>${train_log}
echo "Train End time: $(date)" >>${train_log}
end_time=$(date +%s)
duration=$((end_time - start_time))
hours=$((duration / 3600))
min=$(( (duration % 3600) / 60))
echo "Time elapsed: ${hour}  hour $min min " >>${train_log}
``` 
the run log  as follows : 
<img width="798" alt="image" src="https://github.com/eosphoros-ai/DB-GPT-Hub/assets/26740509/aa5a86a4-4dec-4e6d-be0c-b49ee7943b08">

We can talk further to find the diff  and reason in your env .

**Comment by qidanrui** [comment]
Got it! Thanks, I think it is mainly because of the bit error in Colab Env. Great~!
