### ISSUE TITLE
env -create ,can you provide a conda yml file?

### ISSUE THREAD

**Issue by AOnlineFish** [eosphoros-ai/DB-GPT-Hub#154]
Poetry install is a bit slower than pip. Can you provide an env yml file? @wangzaistone

**Comment by wangzaistone** [comment]
sure,   the file is as follows , and due to the .yml format is not allowed to upload in the github ,  so when you create env , you need to change the format to .yml . 
[Uploading dbgpt_hub.md…]()  
```
move  dbgpt_hub.md  dbgpt_hub.yml 
conda env create -f  dbgpt_hub.yaml
```

**Comment by wangzaistone** [comment]
or use pip ,  `pip install -r requirements.txt `
[requirements.txt](https://github.com/eosphoros-ai/DB-GPT-Hub/files/13524861/requirements.txt)

**Comment by AOnlineFish** [comment]
Okay, thank you very much.

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

2023 年 12 月 1 日星期五 18:50, wangzaistone ***@***.***(mailto:2023 年 12 月 1 日星期五 18:50, wangzaistone <<a href=)> 来信：
