### ISSUE TITLE
can you provide a  requirement.txt instead of poetry install

### ISSUE THREAD

**Issue by wjs0702cn** [eosphoros-ai/DB-GPT-Hub#175]
we have bad network connection to files.pythonhosted.org, but can use proxy like aliyun. 
will you please provide a requirement.txt instead of poetry install?

**Comment by wangzaistone** [comment]
@wjs0702cn  this issue [ issues/168](https://github.com/eosphoros-ai/DB-GPT-Hub/issues/154#issuecomment-1835878200)
