### ISSUE TITLE
Exit without ERROR when sft with multi GPU

### ISSUE THREAD

**Issue by Wolfstewart** [eosphoros-ai/DB-GPT-Hub#189]
When i train sft with multi card , after Running tokenizer on dataset, process exited without error!
![aaa](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/50198593/c4b3076c-0c90-494e-b670-26d09a51d975)

**Comment by junewgl** [comment]
It looks absolutely amazing! Can you provide a training script to reproduce this problem? By the way, will an error be reported when running a single card? @Wolfstewart
