### ISSUE TITLE
in _load_from_state_dict     self.bias.data = bias_data.to(self.bias.data.device) AttributeError: 'NoneType' object has no attribute 'to'

### ISSUE THREAD

**Issue by wangzaistone** [eosphoros-ai/DB-GPT-Hub#193]
error : "/home/anaconda/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 254, in _load_from_state_dict
    self.bias.data = bias_data.to(self.bias.data.device)
AttributeError: 'NoneType' object has no attribute 'to'"
@wangzaistone

**Comment by wangzaistone** [comment]
to solve this , this due to the bitsands verision error , " pip install bitsandbytes --upgrade "  ," Successfully installed bitsandbytes-0.41.3.post2" can solve it ~

**Comment by qidanrui** [comment]
@wangzaistone Need to update poetry? I'll update it.

**Comment by wangzaistone** [comment]
> @wangzaistone Need to update poetry? I'll update it.

update it would be better .

**Comment by qidanrui** [comment]
@wangzaistone please refer to the new pr. tk.
