### ISSUE TITLE
中文模型训练是否支持？

### ISSUE THREAD

**Issue by WeiYue0517** [eosphoros-ai/DB-GPT-Hub#196]
假如想训练中文的模型，是不是需要使用baichuan2的base模型 + CSpider的数据集进行训练？

**Comment by qidanrui** [comment]
是可以的~

**Comment by WljclW** [comment]
为什么处理cspider数据集后，得不到正确的格式，data下也没有文件出现？

**Comment by dusens** [comment]
> 为什么处理cspider数据集后，得不到正确的格式，data下也没有文件出现？

哥们你这个解决了么

**Comment by JonathanHuangC** [comment]
想知道+1
