### ISSUE TITLE
Fine-tuning dataset

### ISSUE THREAD

**Issue by weiwangorg** [eosphoros-ai/DB-GPT-Hub#201]
Hi, I want to ask what data set is used for this 50 thousand pieces of text-to-sql data.
<img width="914" alt="image" src="https://github.com/eosphoros-ai/DB-GPT-Hub/assets/22360336/021e056c-7ea4-45dd-ae5d-e7751cdb9f0d">

**Comment by qidanrui** [comment]
@weiwangorg  Sorry that part of the 50 thousand data cannot be public because of the privacy issue. Currently, you can use public dataset like spider or bird to test our project! Thanks!

**Comment by weiwangorg** [comment]
Ok, thank you.
