### ISSUE TITLE
Checkpoint_dir初始值设置None存在问题

### ISSUE THREAD

**Issue by 123qwe1234512** [eosphoros-ai/DB-GPT-Hub#204]
想要评估未经微调的模型原本的能力，但是在预测时，checkpoint_dir参数一直无法设置正确，设置--checkpoint_dir None\或者--checkpoint_dir \均会报错，请问应该如何设置？有其他需要修改的地方么？

**Comment by qidanrui** [comment]
@wangzaistone 我记得我们现在貌似checkpoint_dir不能设置为空？

**Comment by 123qwe1234512** [comment]
那么应该怎么评估模型原本能力呢，还是必须先拿数据微调才行么？以及想问一下评估结果表格里的base是指某个微调方法还是原模型呢？如果是原模型的话该怎么获得这个结果呢

**Comment by junewgl** [comment]
> 想要评估未经微调的模型原本的能力，但是在预测时，checkpoint_dir参数一直无法设置正确，设置--checkpoint_dir None\或者--checkpoint_dir \均会报错，请问应该如何设置？有其他需要修改的地方么？

可以设置为空，直接不传这个checkpoint_dir参数即可。 @123qwe1234512 cc @qidanrui

**Comment by junewgl** [comment]
> 那么应该怎么评估模型原本能力呢，还是必须先拿数据微调才行么？以及想问一下评估结果表格里的base是指某个微调方法还是原模型呢？如果是原模型的话该怎么获得这个结果呢

如果要评估基础LLM的能力，直接predict即可，不需要经过数据微调/
base指的是最基础的LLM，没有经过任何微调。 @123qwe1234512

**Comment by 123qwe1234512** [comment]
> > 想要评估未经微调的模型原本的能力，但是在预测时，checkpoint_dir参数一直无法设置正确，设置--checkpoint_dir None\或者--checkpoint_dir \均会报错，请问应该如何设置？有其他需要修改的地方么？
> 
> 可以设置为空，直接不传这个checkpoint_dir参数即可。 @123qwe1234512 cc @qidanrui

好的，谢谢，删掉那一行之后ok了（真的记得之前也试过删掉这行但是报错来着，但是这次删掉之后就可以正常的一条条预测了）

**Comment by goy-jin** [comment]
> > > 想要评估未经微调的模型原本的能力，但是在预测时，checkpoint_dir参数一直无法设置正确，设置--checkpoint_dir None\或者--checkpoint_dir \均会报错，请问应该如何设置？有其他需要修改的地方么？
> > 
> > 
> > 可以设置为空，直接不传这个checkpoint_dir参数即可。 @123qwe1234512 cc @qidanrui
> 
> 好的，谢谢，删掉那一行之后ok了（真的记得之前也试过删掉这行但是报错来着，但是这次删掉之后就可以正常的一条条预测了）
参数设置：
CUDA_VISIBLE_DEVICES=0,1 python dbgpt_hub_sql/predict/predict.py \
--model_name_or_path /home/ren/Finetuning/Qwen-1_8B-Chat \
--template chatml \
--finetuning_type lora \
--predicted_input_filename dbgpt_hub_sql/data/example_text2sql_dev.json \
# --checkpoint_dir dbgpt_hub_sql/output/adapter/CodeLlama-13b-sql-lora \
--predicted_out_filename dbgpt_hub_sql/output/pred/pred_qwen.sql >> ${pred_log}
## --predicted_out_filename dbgpt_hub_sql/output/pred/pred_codellama13b.sql >> ${pred_log}
运行结果：
(dbgpt_hub) ren[@ren](https://space.bilibili.com/31601):~/DB-GPT-Hub/src/dbgpt-hub-sql/dbgpt_hub_sql/scripts$ bash predict_sft.sh
predict_sft.sh: 行 6: dbgpt_hub_sql/output/logs/pred_test_20241209_1555.log: 没有那个文件或目录
predict_sft.sh: 行 8: dbgpt_hub_sql/output/logs/pred_test_20241209_1555.log: 没有那个文件或目录
predict_sft.sh: 行 16: dbgpt_hub_sql/output/logs/pred_test_20241209_1555.log: 没有那个文件或目录
predict_sft.sh: 行 17: dbgpt_hub_sql/output/logs/pred_test_20241209_1555.log: 没有那个文件或目录
predict_sft.sh: 行 22: dbgpt_hub_sql/output/logs/pred_test_20241209_1555.log: 没有那个文件或目录
但dbgpt_hub_sql/output/logs/存在，不知道哪里出错了
