### ISSUE TITLE
RuntimeError: expected scalar type Float but found BFloat16

### ISSUE THREAD

**Issue by yoguoo** [eosphoros-ai/DB-GPT-Hub#206]

**Comment by junewgl** [comment]
If you can provide complete error information, the running environment and running steps, we can reproduce the problem and solve it faster @yoguoo

**Comment by yoguoo** [comment]
> If you can provide complete error information, the running environment and running steps, we can reproduce the problem and solve it faster @yoguoo 


i set config to bf16 but the i find adpter parameter is fp16，and input x is fp32

**Comment by junewgl** [comment]
> > If you can provide complete error information, the running environment and running steps, we can reproduce the problem and solve it faster @yoguoo
> 
> i set config to bf16 but the i find adpter parameter is fp16，and input x is fp32

What is your running script? What is the complete error message? @yoguoo

**Comment by yoguoo** [comment]
> > > If you can provide complete error information, the running environment and running steps, we can reproduce the problem and solve it faster @yoguoo
> > 
> > 
> > i set config to bf16 but the i find adpter parameter is fp16，and input x is fp32
> 
> What is your running script? What is the complete error message? @yoguoo

from dbgpt_hub.data_process import preprocess_sft_data
from dbgpt_hub.train import start_sft
from dbgpt_hub.predict import start_predict
from dbgpt_hub.eval import start_evaluate

# 配置训练和验证集路径和参数
data_folder = "dbgpt_hub/data"
data_info = [
        {
            "data_source": "spider",
            "train_file": ["train_spider.json", "train_others.json"],
            "dev_file": ["dev.json"],
            "tables_file": "tables.json",
            "db_id_name": "db_id",
            "is_multiple_turn": False,
            "train_output": "spider_train.json",
            "dev_output": "spider_dev.json",
        }
]

# 配置fine-tune参数
train_args = {
            "model_name_or_path": "/home/AIlab/.cache/modelscope/hub/AI-ModelScope/CodeLlama-7b-hf",
            "do_train": True,
            "dataset": "example_text2sql_train",
            "max_source_length": 2048,
            "max_target_length": 512,
            "finetuning_type": "lora",
            "lora_target": "q_proj,v_proj",
            "template": "llama2",
            "lora_rank": 64,
            "lora_alpha": 32,
            "output_dir": "dbgpt_hub/output/adapter/CodeLlama-13b-sql-lora",
            "overwrite_cache": True,
            "overwrite_output_dir": True,
            "per_device_train_batch_size": 1,
            "gradient_accumulation_steps": 16,
            "lr_scheduler_type": "cosine_with_restarts",
            "logging_steps": 50,
            "save_steps": 2000,
            "learning_rate": 2e-4,
            "num_train_epochs": 8,
            "plot_loss": True,
            "bf16": True,
}

# 配置预测参数
predict_args = {
            "model_name_or_path": "/home/AIlab/.cache/modelscope/hub/AI-ModelScope/CodeLlama-7b-hf/",
            "template": "llama2",
            "finetuning_type": "lora",
            "checkpoint_dir": "dbgpt_hub/output/adapter/CodeLlama-13b-sql-lora",
            "predict_file_path": "dbgpt_hub/data/eval_data/dev_sql.json",
            "predict_out_dir": "dbgpt_hub/output/",
            "predicted_out_filename": "pred_sql.sql",
}

# 配置评估参数
evaluate_args =  {
            "input": "./dbgpt_hub/output/pred/pred_sql_dev_skeleton.sql",
            "gold": "./dbgpt_hub/data/eval_data/gold.txt",
            "gold_natsql": "./dbgpt_hub/data/eval_data/gold_natsql2sql.txt",
            "db": "./dbgpt_hub/data/spider/database",
            "table": "./dbgpt_hub/data/eval_data/tables.json",
            "table_natsql": "./dbgpt_hub/data/eval_data/tables_for_natsql2sql.json",
            "etype": "exec",
            "plug_value": True,
            "keep_distict": False,
            "progress_bar_for_each_datapoint": False,
            "natsql": False,
}

# 执行整个Fine-tune流程
preprocess_sft_data(
      data_folder = data_folder,
      data_info = data_info
)

start_sft(train_args)
start_predict(predict_args)
start_evaluate(evaluate_args)

errro is：    result = F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bias)
RuntimeError: expected scalar type Float but found BFloat16

**Comment by wangzaistone** [comment]
what's the type of  your GPU ?

**Comment by yoguoo** [comment]
> what's the type of your GPU ?

a800, support bf16, but the input is torch.float32

**Comment by yoguoo** [comment]
![image](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/90297776/9b7ba9aa-2440-47a8-9ebc-64d662f6645e)

**Comment by yoguoo** [comment]
> ![image](https://private-user-images.githubusercontent.com/90297776/294112403-9b7ba9aa-2440-47a8-9ebc-64d662f6645e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNTMzMDYsIm5iZiI6MTcwNDM1MzAwNiwicGF0aCI6Ii85MDI5Nzc3Ni8yOTQxMTI0MDMtOWI3YmE5YWEtMjQ0MC00N2E4LTllYmMtNjRkNjYyZjY2NDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDA3MjMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NDlmZTY1ZjM5MTI4MGJjODM3OGU4Y2YxNjBmYjlmODNmODNkNjFkNmE3OWQ4ZmRlN2YzYmMwNjM5OTA3MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tf3z7EeAzWfDBROiVYh9f8R4V4GV1Du4Oda2O3wT9_k)

i dont know why it return fp32
