### ISSUE TITLE
执行poetry install下载报错

### ISSUE THREAD

**Issue by Yokixixi** [eosphoros-ai/DB-GPT-Hub#210]
![b4635c57b308333ae83b09f6a78a4b2](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/47922308/7737e070-ae9f-4c4a-baa9-56ef15ec2e1c)

**Comment by idontknowfishing** [comment]
poetry export -f requirements.txt --output requirements.txt --without-hashes
pip install -r requirements.txt

**Comment by likenamehaojie** [comment]
我这有同样的问题 @idontknowfishing 哥们你的问题解决了么？

**Comment by idontknowfishing** [comment]
@likenamehaojie 按照我之前说把poetry转换成requirements用pip就可以了

**Comment by vincegao09** [comment]
对，pip install 时候加上 -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by vincegao09** [comment]
对，pip install 时候加上 -i https://pypi.tuna.tsinghua.edu.cn/simple
