### ISSUE TITLE
Provided path (dbgpt_hub/output/adapter/Qwen-14B-Chat-sql-lora) does not contain a LoRA weight.

### ISSUE THREAD

**Issue by Z-Diviner** [eosphoros-ai/DB-GPT-Hub#214]
在进行Qwen的Lora微调的时候，运行完之后发现在output德对应文件夹下没有adapter_model文件，导致无法进行权重合并？

**Comment by wangzaistone** [comment]
You can check to see if you have performed the export merge operation of the adapter and basic files by referring to the content in the readme.
你可以看下是否已经参照readme中的内容，进行了adapter和基础文件的export merge 操作

**Comment by Z-Diviner** [comment]
![image](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/130019806/d31ce1f8-63aa-4ef8-bb43-d4df6c9dc07b)

**Comment by Z-Diviner** [comment]
您好，好像是训练完毕的时候就没有产生adapter_model.bin文件？

**Comment by tianyouyangying** [comment]
我也遇到这个问题 请问是怎么解决的呢

**Comment by zhangsone** [comment]
> 您好，好像是训练完毕的时候就没有产生adapter_model.bin文件？

我也是遇到了一样的问题，请问大家都是怎么解决的啊

**Comment by zhangsone** [comment]
> 我也遇到这个问题 请问是怎么解决的呢

请问这个问题你解决了嘛，我也遇到了一样的

**Comment by ychuest** [comment]
> > 我也遇到这个问题 请问是怎么解决的呢
> 
> 请问这个问题你解决了嘛，我也遇到了一样的

你好，请问你解决了吗

**Comment by ychuest** [comment]
用下面的代码转换一下（亲测有效）：
from safetensors.torch import load_file
import torch
lora_model_path = 'adapter_model.safetensors'
bin_model_path = 'adapter_model.bin'

torch.save(load_file(lora_model_path), bin_model_path)
