### ISSUE TITLE
ValueError: Target modules [] not found in the base model. Please check the target modules and try again.

### ISSUE THREAD

**Issue by lzq603** [eosphoros-ai/DB-GPT-Hub#22]
(dbgpt_hub) xx@xx-System-deepLearning-pc:~/DB-GPT-Hub-main$ python src/train/train_qlora.py --model_name_or_path /home/ls/ChatGLM2-6B-main/chatglm2-6b

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/ls/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/ls/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/ls/anaconda3/envs/dbgpt_hub did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11.7/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/ls/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
loading base model /home/ls/ChatGLM2-6B-main/chatglm2-6b...
/home/ls/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/configuration_utils.py:483: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
/home/ls/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/modeling_utils.py:2193: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
You are loading your model in 8bit or 4bit but no linear modules were found in your model. Please double check your model architecture, or submit an issue on github if you think this is a bug.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:09<00:00,  1.41s/it]
adding LoRA modules...
Traceback (most recent call last):
  File "/home/ls/DB-GPT-Hub-main/src/train/train_qlora.py", line 831, in <module>
    train()
  File "/home/ls/DB-GPT-Hub-main/src/train/train_qlora.py", line 667, in train
    model = get_accelerate_model(args, checkpoint_dir)
  File "/home/ls/DB-GPT-Hub-main/src/train/train_qlora.py", line 328, in get_accelerate_model
    model = get_peft_model(model, config)
  File "/home/ls/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/peft/mapping.py", line 98, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
  File "/home/ls/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/peft/peft_model.py", line 893, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/home/ls/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/peft/peft_model.py", line 112, in __init__
    self.base_model = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type](
  File "/home/ls/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/peft/tuners/lora.py", line 180, in __init__
    self.add_adapter(adapter_name, self.peft_config[adapter_name])
  File "/home/ls/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/peft/tuners/lora.py", line 194, in add_adapter
    self._find_and_replace(adapter_name)
  File "/home/ls/anaconda3/envs/dbgpt_hub/lib/python3.10/site-packages/peft/tuners/lora.py", line 356, in _find_and_replace
    raise ValueError(
ValueError: Target modules [] not found in the base model. Please check the target modules and try again.
(dbgpt_hub) xx@xx-System-deepLearning-pc:~/DB-GPT-Hub-main$

**Comment by zhanghy-sketchzh** [comment]
chatglm2-6b is not yet fully adapted. To solve this problem, you can set Target modules to None, and the code will automatically assign modules

**Comment by Calajv** [comment]
I have encountered the same problem, how did you solved the problem?
