### ISSUE TITLE
请问怎么用bird数据集微调codellama呢？

### ISSUE THREAD

**Issue by Mucalinda2436** [eosphoros-ai/DB-GPT-Hub#223]
具体要在哪些地方改动？

**Comment by wangyongshuai88** [comment]
同问，求解答

**Comment by wangzaistone** [comment]
You can main refer the code as follows : https://github.com/eosphoros-ai/DB-GPT-Hub/blob/0f558a3220d7099bbb2ac8e7271404bf86bedde9/dbgpt_hub/configs/config.py#L60
