### ISSUE TITLE
三张3090卡可以不开量化用lora在BIRD数据集上微调吗

### ISSUE THREAD

**Issue by Mucalinda2436** [eosphoros-ai/DB-GPT-Hub#228]
deepspeed --include localhost:1,7,0  dbgpt_hub/train/sft_train.py \
    --deepspeed dbgpt_hub/configs/ds_config.json \
    --model_name_or_path $model_name_or_path \
    --do_train \
    --dataset example_text2sql_train \
    --max_source_length 1024 \
    --max_target_length 512 \
    --template llama2 \
    --finetuning_type lora \
    --lora_rank 64 \
    --lora_alpha 32 \
    --lora_target q_proj,v_proj \
    --output_dir $output_dir \
    --overwrite_cache \
    --overwrite_output_dir \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --lr_scheduler_type cosine_with_restarts \
    --logging_steps 25 \
    --save_steps 20 \
    --learning_rate 2e-4 \
    --num_train_epochs 0.1 \
    --plot_loss \
    --bf16 2>&1 | tee ${train_log}
这是我的参数，但是显示显存超了，不开量化三张卡都不够嘛？我batchsize都已经是1了

**Comment by linjingran01** [comment]
同问题，不开量化多卡不能跑

**Comment by Mucalinda2436** [comment]
> 同问题，不开量化多卡不能跑

我后来选择了QLora来微调，效果也不错的

**Comment by linjingran01** [comment]
> > 同问题，不开量化多卡不能跑
> 
> 我后来选择了QLora来微调，效果也不错的

你是在CodeLlama2-13b上微调的吗？num_train_epochs设置多少轮？数据集是通用问答还是SQL问答？
