### ISSUE TITLE
CUDA kernel errors might be asynchronously reported at some other API call

### ISSUE THREAD

**Issue by muruan01** [eosphoros-ai/DB-GPT-Hub#23]
I run the finetune code, and found this error, does anyone can help?
File ~/.local/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py:88, in LlamaRMSNorm.forward(self, hidden_states)
     85 variance = hidden_states.to(torch.float32).pow(2).mean(-1, keepdim=True)
     86 hidden_states = hidden_states * torch.rsqrt(variance + self.variance_epsilon)
---> 88 return (self.weight * hidden_states).to(input_dtype)

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

The error code is from train() function.

**Comment by wangzaistone** [comment]
> 
you can change the command in the script ， where is  scripts/spider_qlora_finetune.sh ,   before ` python src/train/train_qlora.py \ ` , add your  definate card , like “CUDA_VISIBLE_DEVICES=1,2,3 python src/train/train_qlora.py \”
