### ISSUE TITLE
可以公开一下hugging face上的lora模块的微调参数吗

### ISSUE THREAD

**Issue by Mucalinda2436** [eosphoros-ai/DB-GPT-Hub#230]
想用同样的数据微调一个bird数据集，最好有deepspeed版的微调参数

**Comment by wangzaistone** [comment]
> 想用同样的数据微调一个bird数据集，最好有deepspeed版的微调参数

用的就是公开的默认参数，deepspeed的配置在最新的readme中增加了相关说明
