### ISSUE TITLE
模型训练完进行合并权重时，显示does not contain a LoRA weight

### ISSUE THREAD

**Issue by zhuyubaiyu** [eosphoros-ai/DB-GPT-Hub#232]
![Snipaste_2024-02-04_17-16-04](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/20263469/596ddc3a-a0d6-4ecf-8c80-72a822b7c23b)
这个是Qwen-14B-chat_int4模型训练完生成的文件，在权重合并是报错AssertionError: Provided path (/home/user/netdisk/DB-GPT/models/chatglm2-6b/output/adapter) does not contain a LoRA weight.

**Comment by GuohuanFeng0** [comment]
请问解决了吗

**Comment by ychuest** [comment]
> 请问解决了吗

你好，请问解决了吗

**Comment by ychuest** [comment]
用下面的代码转换一下（亲测有效）：
from safetensors.torch import load_file
import torch
lora_model_path = 'adapter_model.safetensors'
bin_model_path = 'adapter_model.bin'

torch.save(load_file(lora_model_path), bin_model_path)
