### ISSUE TITLE
Prompt for CodeLlama model

### ISSUE THREAD

**Issue by tail-recursion** [eosphoros-ai/DB-GPT-Hub#234]
Hi, would Code Llama use the Llama 2 template? I would appreciate if someone could provide an example of the prompt used for Code Llama. I tried running the Code Llama 13b fine tune I found on Hugging Face and I only get about 50% execution accuracy overall on spider/evaluation_examples/dev.sql.

I used the prompt found here: https://huggingface.co/machinists/CodeLlama-13b-Instruct-SQL

In my experience these models are very sensitive to the prompt so I want to see if I can use the same prompt used in your evaluation and get a better execution accuracy.

**Comment by wangzaistone** [comment]
"would Code Llama use the Llama 2 template? ", it's sure.  Our project has already provided a  code llama prompt  ,  you can refer  the code as follows  https://github.com/eosphoros-ai/DB-GPT-Hub/blob/67175bc7593e7892d265bfc28df403145ed44c09/dbgpt_hub/configs/config.py#L100
