### ISSUE TITLE
网页刷新后 每个会话的模型选择恢复到默认模型  无法模型选择记忆化

### ISSUE THREAD

**Issue by wxy1105952676** [eosphoros-ai/DB-GPT-Hub#235]
### 网页刷新一下后 会话无法记住上次选择的模型和知识库
![3](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/63040615/3251dc01-8e7f-4949-8cec-f143456b858c)

# 请问这个问题(如图)目前有解决方案吗？

**Comment by wangzaistone** [comment]
@wxy1105952676 这个是主项目的内容？ issue可以给到DB-GPT

**Comment by Dingzhen778** [comment]
老哥，想知道你是怎么实现模型切换的啊，在.env文件设置的吗？我这边有好几个模型都想通过api和proxyllm代理实现，但总是只有一个模型生效，求告知
