### ISSUE TITLE
Can we support the sqlcoder-7b-2

### ISSUE THREAD

**Issue by yourchanges** [eosphoros-ai/DB-GPT-Hub#245]
The sqlcoder-7b-2's model weights were updated at 7 AM UTC on Feb 7, 2024. The new model weights lead to a much more performant model – particularly for joins. 

https://huggingface.co/defog/sqlcoder-7b-2

![image](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/492946/ad62b8a9-e0b3-4c58-b2bf-74e563ce9283)

So, can we support the sqlcoder-7b-2?

**Comment by wangzaistone** [comment]
@yourchanges  We have supported  sqlcoder2， you can find related config in readme.

<br class="Apple-interchange-newline">
