### ISSUE TITLE
If the fine-tuned model could be used to DB-GPT?

### ISSUE THREAD

**Issue by nibnahzuh** [eosphoros-ai/DB-GPT-Hub#246]
A series of models, including GPTs, are prone to generating poor quality SQL during the Text to SQL phase of complex data analysis tasks. It seems that the fine tuned model has better SQL writing ability. Can the fine tuned model be applied to the DB-GPT project？

**Comment by wangzaistone** [comment]
Yes, just like use the other orgin llm like  origin qwen,baichuan

**Comment by wangzaistone** [comment]
Yes, just like use the other orgin llm like  origin qwen,baichuan
