### ISSUE TITLE
torch.cuda.OutOfMemoryError

### ISSUE THREAD

**Issue by yilia1828** [eosphoros-ai/DB-GPT-Hub#248]
使用dbgp_hubt提供的微调代码，基于数据集spider对chatglm3-6b进行微调，但是报显存溢出（4090显卡），报错如下：
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 214.00 MiB. GPU 0 has a total capacity of 23.64 GiB of which 170.69 MiB is free. Including non-PyTorch memory, this process has 23.28 GiB memory in use. Of the allocated memory 22.74 GiB is allocated by PyTorch, and 136.85 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

参数如下：
train_args = {
            "model_name_or_path": "/usr/local/src/models/chatglm3-6b",
            "do_train": True,
            "dataset": "example_text2sql_train",
            "max_source_length": 2048,
            "max_target_length": 512,
            "finetuning_type": "lora",
            "lora_target": "query_key_value",
            "template": "chatglm3",
            "lora_rank": 64,
            "lora_alpha": 32,
            "output_dir": "/usr/local/src/DB-GPT-Hub/dbgpt_hub/output/adapter/chatglm3-6b-sql-lora",
            "overwrite_cache": True,
            "overwrite_output_dir": True,
            "per_device_train_batch_size": 1,
            "gradient_accumulation_steps": 16,
            "lr_scheduler_type": "cosine_with_restarts",
            "logging_steps": 50,
            "save_steps": 2000,
            "learning_rate": 2e-4,
            "num_train_epochs": 8,
            "plot_loss": True,
            "bf16": True,
}
求教各位大佬，有什么解决办法？

**Comment by wangzaistone** [comment]
@yilia1828 在资源实在有限的情况下，相关参数可以设置的小点，比如"lora_rank": 64,"lora_alpha": 32,
