### ISSUE TITLE
很棒的工作，请问现在支持chatGLM2-6B的微调吗

### ISSUE THREAD

**Issue by ldxbaby756** [eosphoros-ai/DB-GPT-Hub#32]

**Comment by zhanghy-sketchzh** [comment]
Not yet, but this is in our plan. If you need to use Chinese, you can use vicuna model

**Comment by ldxbaby756** [comment]
感谢回复，我在微调的时候碰到了两个问题，

**Comment by ldxbaby756** [comment]
感谢回复，我在微调的时候碰到了两个问题：
1、我用的模型是https://huggingface.co/Tribbiani/vicuna-13b，请问我用对了么；
2、我在微调的时候碰到报错如下，我依赖也是按照requirements装的。期待回复~
{'loss': 2.4173, 'learning_rate': 0.0002, 'epoch': 0.02}                                                                                                      
{'loss': 1.2451, 'learning_rate': 0.0002, 'epoch': 0.04}                                                                                                      
{'loss': 1.6442, 'learning_rate': 0.0002, 'epoch': 0.06}                                                                                                      
{'loss': 1.5537, 'learning_rate': 0.0002, 'epoch': 0.08}                                                                                                      
{'loss': 1.6861, 'learning_rate': 0.0002, 'epoch': 0.1}                                                                                                       
{'loss': 1.2466, 'learning_rate': 0.0002, 'epoch': 0.12}                                                                                                      
{'loss': 1.0065, 'learning_rate': 0.0002, 'epoch': 0.14}                                                                                                      
{'loss': 1.4067, 'learning_rate': 0.0002, 'epoch': 0.16}                                                                                                      
{'loss': 1.343, 'learning_rate': 0.0002, 'epoch': 0.18}                                                                                                       
{'loss': 1.5804, 'learning_rate': 0.0002, 'epoch': 0.21}                                                                                                      
{'loss': 1.1822, 'learning_rate': 0.0002, 'epoch': 0.23}                                                                                                      
{'loss': 0.9773, 'learning_rate': 0.0002, 'epoch': 0.25}                                                                                                      
{'loss': 1.2288, 'learning_rate': 0.0002, 'epoch': 0.27}                                                                                                      
{'loss': 1.3508, 'learning_rate': 0.0002, 'epoch': 0.29}                                                                                                      
{'loss': 1.4149, 'learning_rate': 0.0002, 'epoch': 0.31}                                                                                                      
{'loss': 1.1256, 'learning_rate': 0.0002, 'epoch': 0.33}                                                                                                      
{'loss': 0.8991, 'learning_rate': 0.0002, 'epoch': 0.35}                                                                                                      
{'loss': 1.0216, 'learning_rate': 0.0002, 'epoch': 0.37}                                                                                                      
 10%|███████████▎                                                                                                     | 187/1875 [1:25:32<12:44:26, 27.17s/it]Traceback (most recent call last):
  File "/home/liuduoxing1/NL2SQL/DB-GPT-Hub/train_qlora.py", line 130, in <module>
    main()
  File "/home/liuduoxing1/NL2SQL/DB-GPT-Hub/train_qlora.py", line 91, in main
    train_result = trainer.train()
  File "/home/liuduoxing1/.custom/cuda11.3.1-cudnn8-devel-ubuntu20.04-py38-pytorch1.11-jupyterlab3.2.9/envs/dbgpt/lib/python3.10/site-packages/transformers/trainer.py", line 1531, in train
    return inner_training_loop(
  File "/home/liuduoxing1/.custom/cuda11.3.1-cudnn8-devel-ubuntu20.04-py38-pytorch1.11-jupyterlab3.2.9/envs/dbgpt/lib/python3.10/site-packages/transformers/trainer.py", line 1896, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/home/liuduoxing1/.custom/cuda11.3.1-cudnn8-devel-ubuntu20.04-py38-pytorch1.11-jupyterlab3.2.9/envs/dbgpt/lib/python3.10/site-packages/transformers/trainer.py", line 2220, in _maybe_log_save_evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/home/liuduoxing1/.custom/cuda11.3.1-cudnn8-devel-ubuntu20.04-py38-pytorch1.11-jupyterlab3.2.9/envs/dbgpt/lib/python3.10/site-packages/transformers/trainer_seq2seq.py", line 153, in evaluate
    gen_kwargs["max_length"] = self.args.generation_max_length
AttributeError: 'TrainingArguments' object has no attribute 'generation_max_length'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.

**Comment by zhanghy-sketchzh** [comment]
It seems really a bug, you can try to change the configs/train_args ` class TrainingArguments (transformers. Seq2SeqTrainingArguments) ：
