### ISSUE TITLE
是否支持除SPIDER以外的数据集进行训练？

### ISSUE THREAD

**Issue by jcdiv47** [eosphoros-ai/DB-GPT-Hub#53]
想请问是否支持使用除SPIDER以外的数据集进行训练？

在[介绍数据集](https://github.com/eosphoros-ai/DB-GPT-Hub#21-dataset)的部分看到有声称使用了CoSQL等数据集；目前已成功用SPIDER完成训练，但是在[data-preparation](https://github.com/eosphoros-ai/DB-GPT-Hub#32-data-preparation)部分以及从[处理sql数据集的代码](https://github.com/eosphoros-ai/DB-GPT-Hub/blob/main/dbgpt_hub/utils/sql_data_process.py)出发，在项目里找了很久也不确定如何使用除SPIDER以外的数据集进行训练。

想问下项目是否原生支持用CoSQL等其他数据集训练，或者如果自行训练，要做哪些处理；我这边也会继续研究，如果有需要的话我后续可以尝试PR

**Comment by zhanghy-sketchzh** [comment]
We have not yet processed other data sets, but the specific ideas should be referenced in our work

**Comment by jcdiv47** [comment]
Thanks for the reply. I will close it for now. 

Not sure if it is in the roadmap for the project, I would however really appreciate it if there is some easy-to-follow procedure in the project for users to train/evaluate with their own dataset.
