### ISSUE TITLE
how to get the processed dataset

### ISSUE THREAD

**Issue by Chen-PengF** [eosphoros-ai/DB-GPT-Hub#58]
the sql_data_process.py only can process the Spider, and how to process the other dataset.
Can you share the zip that has been processed , the one you've shared on google cloud drive won't open.

**Comment by zhanghy-sketchzh** [comment]
Most SQL datasets today follow the spider format, which you can run with minor modifications in your code. If you need to use your own dataset, you can also consider converting the data into the instruction dataset format. The Google Cloud Drive data set should be open
