### ISSUE TITLE
Collaborate with ChatGLM-Efficient-Tuning to enable ChatGLM fine-tuning

### ISSUE THREAD

**Issue by simonkorl** [eosphoros-ai/DB-GPT-Hub#63]
Currently, this repository does not support ChatGLM finetuing. However, it is possible to leverage other repositories to fine-tune ChatGLM and evaluate its predictions using sources in this repository. [ChatGLM-Efficient-Tuning](https://github.com/hiyouga/ChatGLM-Efficient-Tuning) (or current [LLaMA-Efficient-Tuning](https://github.com/hiyouga/LLaMA-Efficient-Tuning)) may be a good start.

The whole process of fine-tuning and evaluation is simple:

1. Create Spider dataset following this repo's instruction
2. Fine-tune ChatGLM using other repos like ChatGLM-Efficient-Tuning
3. Evaluate the ChatGLM model using other repos to get predictions
4. Use this repo's evaluation script to evaluate the predictions

I changed the evaluation script a little bit to enable the predicted result's format in ChatGLM-Efficient-Tuning. You can check it using the following link.

https://github.com/simonkorl/DB-GPT-Hub/blob/67de518607b7890e11c1bbe1dc9e637c499392dd/eval/evaluation.py#L664C5-L688C24

All in all, it is fascinating to know that this project will introduce multiple base models and fine-tuning methods. However, it takes time to implement such tools. It might be a contemporary solution to utilize multiple different repos to do the same thing, but I think it is useful for everyone who is interested in this area.

**Comment by csunny** [comment]
Great job, can you submit a PR about this part?
