### ISSUE TITLE
强烈点赞，支持！提示词建议

### ISSUE THREAD

**Issue by highroom** [eosphoros-ai/DB-GPT-Hub#7]
强烈点赞，支持！
另外，之前看了一个资料，提示词可以做成：建表语句+查询语句+3行数据，这样的效果最好，不知道会不会有帮助，有机会可以试试呀

CREATE TABLE "Track" (
"TrackId" INTEGER NOT NULL,
"Name" NVARCHAR(200) NOT NULL,
"AlbumId" INTEGER,
"MediaTypeId" INTEGER NOT NULL,
"GenreId" INTEGER,
"Composer" NVARCHAR(220),
"Milliseconds" INTEGER NOT NULL,
"Bytes" INTEGER,
"UnitPrice" NUMERIC(10, 2) NOT NULL,
PRIMARY KEY ("TrackId"),
FOREIGN KEY("MediaTypeId") REFERENCES "MediaType" ("MediaTypeId"),
FOREIGN KEY("GenreId") REFERENCES "Genre" ("GenreId"),
FOREIGN KEY("AlbumId") REFERENCES "Album" ("AlbumId")
)
SELECT * FROM 'Track' LIMIT 3;
TrackId	Name	AlbumId	MediaTypeId	GenreId	Composer	Milliseconds	Bytes	UnitPrice
1	For Those About To Rock (We Salute You)	1	1	1	Angus Young, Malcolm Young, Brian Johnson	343719	11170334	0.99
2	Balls to the Wall	2	2	1	None	342562	5510424	0.99
3	Fast As a Shark	3	2	1	F. Baltes, S. Kaufman, U. Dirkscneider & W. Hoffman	230619	3990994	0.99

**Comment by csunny** [comment]
Good idea.

**Comment by csunny** [comment]
This idea is really good, and we are also actively exploring various optimization methods. Regarding your proposal,  welcome to participate in and contribute relevant codes. We will build a unified pipeline for continuous finetune.
