### ISSUE TITLE
Target modules ['q_proj', 'v_proj'] not found in the base model.

### ISSUE THREAD

**Issue by HDHD-forever** [eosphoros-ai/DB-GPT-Hub#79]
请问这个报错是什么原因造成的呢
ValueError: Target modules ['q_proj', 'v_proj'] not found in the base model. Please check the target modules and try again.
![image](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/59165001/54a4f9dc-9b99-478f-9808-a0a11dfeb41a)

**Comment by HDHD-forever** [comment]
> > 请问这个报错是什么原因造成的呢 ValueError: Target modules ['q_proj', 'v_proj'] not found in the base model. Please check the target modules and try again. ![image](https://user-images.githubusercontent.com/59165001/269274502-54a4f9dc-9b99-478f-9808-a0a11dfeb41a.png)
> 
> 你训练的模型是什么？

Baichuan2-13B

**Comment by wangzaistone** [comment]
> > 你训练的模型是什么？
> 
> Baichuan2-13B

Baichuan2-13B进行LoRA微调的部分并不是 ['q_proj', 'v_proj'] ，而是W_pack，给参数lora_target 的值为W_pack。命令为：
CUDA_VISIBLE_DEVICES=0 python src/train_bash.py \
    --model_name_or_path Baichuan2-13B-Base \
    --do_train \
    --dataset example_text2sql \
    --max_source_length 1024 \
    --max_target_length 512 \
    --template default \
    --finetuning_type lora \
    --lora_rank 32 \
    --lora_alpha 64 \
    --lora_target W_pack \
    --output_dir path_to_sft_checkpoint \
    --overwrite_cache \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 6.0 \
    --plot_loss \
    --fp16
   这个在train/目录下的Readme中。

**Comment by HDHD-forever** [comment]
看到了，感谢，之前没注意看readme
