### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe wandb: While tearing down the service manager. The following error has occurred: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by zhuxiuling** [eosphoros-ai/DB-GPT-Hub#80]
![image](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/118955945/7373bfdf-b113-4f98-a05e-bb63f4c382a9)
训练时出现这个问题可能是什么原因？

**Comment by wangzaistone** [comment]
> ![image](https://user-images.githubusercontent.com/118955945/269820751-7373bfdf-b113-4f98-a05e-bb63f4c382a9.png) 训练时出现这个问题可能是什么原因？

把wandb关了就可以了。直接wandb offline 或者wandb disable

**Comment by zhuxiuling** [comment]
> > ![image](https://user-images.githubusercontent.com/118955945/269820751-7373bfdf-b113-4f98-a05e-bb63f4c382a9.png) 训练时出现这个问题可能是什么原因？
> 
> 把wandb关了就可以了。直接wandb offline 或者wandb disable

**Comment by zhuxiuling** [comment]
> > ![image](https://user-images.githubusercontent.com/118955945/269820751-7373bfdf-b113-4f98-a05e-bb63f4c382a9.png) 训练时出现这个问题可能是什么原因？
> 
> 把wandb关了就可以了。直接wandb offline 或者wandb disable

谢谢，可以了
