### ISSUE TITLE
LLama2-7b没有微调的效果

### ISSUE THREAD

**Issue by zhuxiuling** [eosphoros-ai/DB-GPT-Hub#89]
![image](https://github.com/eosphoros-ai/DB-GPT-Hub/assets/118955945/b3dab099-b508-40cc-9eba-81ec8579bf98)
感觉很低啊，不知道大家的效果是多少，而且我微调后效果和这个也差不了多少........

**Comment by wangzaistone** [comment]
> ![image](https://user-images.githubusercontent.com/118955945/273802985-b3dab099-b508-40cc-9eba-81ec8579bf98.png) 感觉很低啊，不知道大家的效果是多少，而且我微调后效果和这个也差不了多少........

After fine-tuning, in our exp ,it has been improved  a lot in 13B model

**Comment by gantao21** [comment]
麻烦问下，后面怎么解决的？ 我也是7B 微调感觉没生效一样。

**Comment by zhuxiuling** [comment]
还没解决，不知道哪里出了问题.....




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eosphoros-ai/DB-GPT-Hub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月1日(星期三) 下午3:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eosphoros-ai/DB-GPT-Hub] LLama2-7b没有微调的效果 (Issue #89)





 
麻烦问下，后面怎么解决的？ 我也是7B 微调感觉没生效一样。

**Comment by wangyongshuai88** [comment]
> 建议使用codellama，0.2个epoch就可以达到0.65+的效果
请问code llama 如何微调中文数据集？
