### ISSUE TITLE
环境安装报错

### ISSUE THREAD

**Issue by wangzaistone** [eosphoros-ai/DB-GPT-Hub#9]
1、搭建环境手册有问题。 
原问题：
“pip install -r requirements.txt 
conda create -n dbgpt_hub python=3.10 
conda activate dbgpt_hub”
应该改为：
“
conda create -n dbgpt_hub python=3.10 
conda activate dbgpt_hub
pip install -r requirements.txt 
“
顺序应该调整下。

**Comment by wangzaistone** [comment]
2、pip install -r requirements.txt 中的requirements里面内容，第一条安装很慢，一直卡着时可以通过如下方式解决：
wget https://github.com/huggingface/transformers/archive/refs/tags/v4.30.1.zip
unzip v4.30.1.zip 
cd transformers-4.30.1/
pip install .

**Comment by zhanghy-sketchzh** [comment]
good job

**Comment by wangzaistone** [comment]
0726: 拉取最新的代码(版本[373d1ce])，在多卡环境下运行报错：报错信息“ValueError: You can't train a model that has been loaded in 8-bit precision on a different device than the one you're training on. Make sure you loaded the model on the correct device using for example `device_map={'':torch.cuda.current_device()}you're training on. Make sure you loaded the model on the correct device using for example `device_map={'':torch.cuda.current_device() or device_map={'':torch.xpu.current_device()}” 
修改脚本scripts/spider_qlora_finetune.sh 中，在python src/train/train_qlora.py \ 前面加上指定多卡即可。即改为“CUDA_VISIBLE_DEVICES=1,2,3 python src/train/train_qlora.py \” 
分析： 出错主要问题是在默认配置为开启量化的情况下，由于量化需要多卡同步，目前可以在一开始就专门设置指定。

**Comment by csunny** [comment]
> 1、搭建环境手册有问题。 原问题： “pip install -r requirements.txt conda create -n dbgpt_hub python=3.10 conda activate dbgpt_hub” 应该改为： “ conda create -n dbgpt_hub python=3.10 conda activate dbgpt_hub pip install -r requirements.txt “ 顺序应该调整下。

Can you contributing a pr fix this? @wangzaistone

**Comment by wangzaistone** [comment]
> > 1、搭建环境手册有问题。 原问题： “pip install -r requirements.txt conda create -n dbgpt_hub python=3.10 conda activate dbgpt_hub” 应该改为： “ conda create -n dbgpt_hub python=3.10 conda activate dbgpt_hub pip install -r requirements.txt “ 顺序应该调整下。
> 
> Can you contributing a pr fix this? @wangzaistone

ok ,I tried,add apply for  permission
