### ISSUE TITLE
fine tunning 时关于 bitsandbytes的报错

### ISSUE THREAD

**Issue by lehug** [eosphoros-ai/DB-GPT-Hub#90]
环境：
intel x86,  nvidia 3060, cuda 12.1.
启动微调命令，报错如下
```
AttributeError: /home/server/miniconda3/envs/dbgpt_env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cquantize_blockwise_fp16_nf4
```
中间尝试过 将`cp libbitsandbytes_cuda121.so libbitsandbytes_cpu.so`但是不行，最后看到 requirements.txt里面锁定了bitsandbytes为0.39.0，更改升级到最新版本 0.41.0，然后就不报错啦。

不过显存不足，还是跑不起来~

**Comment by wangzaistone** [comment]
> 环境： intel x86, nvidia 3060, cuda 12.1. 启动微调命令，报错如下
> 
> ```
> AttributeError: /home/server/miniconda3/envs/dbgpt_env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cquantize_blockwise_fp16_nf4
> ```
> 
> 中间尝试过 将`cp libbitsandbytes_cuda121.so libbitsandbytes_cpu.so`但是不行，最后看到 requirements.txt里面锁定了bitsandbytes为0.39.0，更改升级到最新版本 0.41.0，然后就不报错啦。
> 
> 不过显存不足，还是跑不起来~

试下7B 的大小的模型，用qlora ,参数带着 ”  --quantization_bit 4 \ “ ，参数max_source_length 的值 由1024改为512

**Comment by GuohuanFeng0** [comment]
> 环境： intel x86, nvidia 3060, cuda 12.1. 启动微调命令，报错如下
> 
> ```
> AttributeError: /home/server/miniconda3/envs/dbgpt_env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cquantize_blockwise_fp16_nf4
> ```
> 
> 中间尝试过 将`cp libbitsandbytes_cuda121.so libbitsandbytes_cpu.so`但是不行，最后看到 requirements.txt里面锁定了bitsandbytes为0.39.0，更改升级到最新版本 0.41.0，然后就不报错啦。
> 
> 不过显存不足，还是跑不起来~

您好 请问一下怎么升级到最新版本的

**Comment by lehug** [comment]
@GuohuanFeng0 requirements.txt里面改版本号，然后重新`pip install`或者在你环境里面`pip install bitsandbytes --upgrade`
