### ISSUE TITLE
fine tuning

### ISSUE THREAD

**Issue by sangdhua** [eosphoros-ai/DB-GPT-Hub#92]
I run this code:  sh dbgpt_hub/scripts/train_sft.sh
it seems I need the dbgpt_hub.py file.
I get the following error:
sh dbgpt_hub/scripts/train_sft.sh

dbgpt_hub/scripts/train_sft.sh: line 1: wandb: command not found

Traceback (most recent call last):

  File "/opt/app/mpidatasci/Sang.Hua/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 6, in <module>

    from dbgpt_hub.llm_base.loggings import LogCallback,get_logger

ModuleNotFoundError: No module named 'dbgpt_hub'

**Comment by wangzaistone** [comment]
The first error is because you don't have install  pkg   wandb , try pip install -r ./requirements.txt    .  In the requirements.txt ,it  has listed wanded include
The scconde error is because path error ,in the lated code version ,in dbgpt_hub/train/sft_train.py  ,we have add the code "
import os    
import sys    
ROOT_PATH = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  
sys.path.append(ROOT_PATH)    
"

**Comment by sangdhua** [comment]
I added the code below to dbgpt_hub/train/sft_train.py and I still get the error message.
import os
import sys
ROOT_PATH = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(file))))
sys.path.append(ROOT_PATH)

**Comment by wangzaistone** [comment]
> I added the code below to dbgpt_hub/train/sft_train.py and I still get the error message. import os import sys ROOT_PATH = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(file)))) sys.path.append(ROOT_PATH)

wandp package has installed ?

**Comment by sangdhua** [comment]
What version should I install?
pip install wandp

ERROR: Could not find a version that satisfies the requirement wandp (from versions: none)

ERROR: No matching distribution found for wandp

**Comment by wangzaistone** [comment]
sorry,It's wandb, pip install wandb

**Comment by sangdhua** [comment]
I still have the same message.  Do you have the dbgpt_hub module that I can put in the right folder?  That might fix the problem.
File "/opt/app/mpidatasci/Sang.Hua/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 6, in <module>

    from dbgpt_hub.llm_base.loggings import LogCallback,get_logger

ModuleNotFoundError: No module named 'dbgpt_hub'

**Comment by wangzaistone** [comment]
> I still have the same message. Do you have the dbgpt_hub module that I can put in the right folder? That might fix the problem. File "/opt/app/mpidatasci/Sang.Hua/DB-GPT-Hub/dbgpt_hub/train/sft_train.py", line 6, in
> 
> ```
> from dbgpt_hub.llm_base.loggings import LogCallback,get_logger
> ```
> 
> ModuleNotFoundError: No module named 'dbgpt_hub'

what's your command  when it reported this error ? 
as our instruciton in README ,   in  DB-GPT-Hub dir , run `sh dbgpt_hub/scripts/train_sft.sh` , I haved tested again ,that's passed

**Comment by wangzaistone** [comment]
May be you need to  get the latest version
