### ISSUE TITLE
请问这个项目的微调训练，除了能做Text2SQL的微调，还能做其他数据集的微调吗？

### ISSUE THREAD

**Issue by HDHD-forever** [eosphoros-ai/DB-GPT-Hub#94]

**Comment by wangzaistone** [comment]
this is a framework mainly focus on text2sql by LLM, may be you can try finetune other task by change the code you need

**Comment by csunny** [comment]
项目目前主要聚焦在Text2SQL方向，如果要做其他微调可以参考一下另一个项目。https://github.com/hiyouga/LLaMA-Efficient-Tuning
